project:
  type: website

website:
  title: "iondata"
  navbar:
    right:
    - href: index.qmd
      text: Home
    - href: index.qmd#about
      text: About
    - href: index.qmd#contact
      text: Contact
    pinned: true
  search: false
  page-footer: "Copyright 2023-2025, iondata Sàrl"

format:
  html:
    theme: zephyr
    css: styles.css
    #backgroundcolor: rgb(196,209,255)
    page-layout: full
    link-external-newwindow: true
editor: visual

