project:
  type: website

website:
  title: "iondata"
  navbar:
    right:
    - href: index.qmd
      text: Home
    - href: index.qmd#about
      text: About
    - href: index.qmd#contact
      text: Contact
    pinned: true
  repo-url: "https://github.com/mibratt"
  search: false
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    center: "&copy; Copyright 2025, iondata Sàrl"
    left: 
      - icon: github
        href: https://github.com/mibratt/

    

format:
  html:
    theme: zephyr
    css: styles.css
    #backgroundcolor: rgb(196,209,255)
    page-layout: full
    link-external-newwindow: true
editor: visual

